### PR TITLE
Updates to build system for use in CI on Parallelworks

### PR DESCRIPTION
**Pull request by laurenchilutti**
These updates allow for more flexibility in the SHiELD build system.  These changes are required for CI.  A summary of the changes:

- The permissions on the scripts in RTS/CI are changed to be executable
- Added an optional argument to the RTS/CI scripts.  This argument is a container command e.g. ```--mpi=pmi2 singularity exec -B <file directory> <container>```
- Some files needed to have bash headers as opposed to sh
- Kept any use of modules to the site environment files
- Updated the way LIBS and INCLUDE are set in intel.mk for netcdf.  This adds support for environments where netcdf-fortran and netcdf-c are not installed into the same directory.

### CODE REVIEW

**Review by bensonr — COMMENTED** [review]
The changes to everything looks good.  I think we need to clean up the netcdf logic a little more in intel.mk and don't forget about gnu.mk.  I see the case where we have 
 - both netcdf-c and netcdf-fortran
 - netcdf/4.x isn't in the modules path
 - default to catch an old netcdf/3.x version

I think we can get away with a check for one case,  plus the fallback
 - _nc-config --libs_ is not empty
    -  same or different prefix doesn't matter
    - construct the INCLUDE and LIBS  using combo of nc-config and nf-config
- default case
    -  construct INCLUDE via NETCDF_ROOT and libs with extended lib-list

**Comment by laurenchilutti** [comment]
Im working on testing the changes you suggested now - for the default case you say "construct INCLUDE via NETCDF_ROOT and libs with extended lib-list"  I interpret this as: 
```INCLUDE = -I$(NETCDF_ROOT)/include```
```LIBS += -lnetcdff -lnetcdf -lhdf5_hl -lhdf5 -lz```
Can you confirm this is what we should do by default?

Thanks!

**Comment by laurenchilutti** [comment]
I just pushed some changes - I have tested the intel build on parallelworks, gaea, and our AMD box.

**Review by bensonr — APPROVED** [review]

**Review by bensonr — APPROVED** [review]
Looks good

**Pull request merged**
